### ISSUE TITLE
Designing Models

### ISSUE THREAD

**Issue by ImamHossainRoni** [iamashraful/try-ecommerce#3]
**Category**

1. CatId
2.CatName

**Brand**

1. BrandId
2.BrandName

**Product**

1. ProductId
2.ProductName
3.Images
4.Specifications
5.Price
6.Review

-----Remaining........

**Comment by iamashraful** [comment]
**NOTE** Please don't use *BrandId*, *ProductId* like this. Use *id* only instead of them
